ent-ClothingUniformRandom = { ent-ClothingUniformBase }
    .desc = Generated by neural networks based on the latest fashion trends.
    .suffix = Random visual

ent-ClothingRandomSpawner = random colorful costume
    .desc = { "" }

ent-ClothingUniformRandomArmless = colorful hands-free costume
    .desc = { "" }

ent-ClothingUniformRandomStandart = colorful costume
    .desc = { "" }

ent-ClothingUniformRandomBra = colorful bra
    .desc = { "" }

ent-ClothingUniformRandomShorts = colorful pants
    .desc = { "" }

ent-ClothingUniformRandomShirt = colorful costume
    .desc = { "" }
